"""
Assignment 1: Standard Input and Output
By: Lew Griffith

This program is the Hangman Game.

The task is to write a program that prints various stages/gallows of the Hangman Game.
"""
print("Hello welcome to the Hangman Game!")
name=input("What is your name? ")
print("Why, Hello" , name,"!")
print("The hangman game is under construction. Maybe you’ll get\nto play it in a few weeks. This is what various stages of\nthe game will look like…")
print()
print('Rules:')
print('As a reminder, the rules of the game are to guess a letter\nof the chosen word. If the suggested letter is not in the\nword, then a head is drawn. Each guessed letter that is not\nin the word will result in another limb being drawn. If you\nfiqure out the word before you reach Stage 6, then you win,\notherwise, you lose.')
print()
print("Stage 0")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|')
print('\t|')
print('\t|')
print('\t|')
print('\t|')
print('\t-------------')
print()
print("Stage 1")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|         O')
print('\t|')
print('\t|')
print('\t|')
print('\t|')
print('\t-------------')
print()
print("Stage 2")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|         O')
print('\t|         |')
print('\t|         |')
print('\t|')
print('\t|')
print('\t|')
print('\t-------------')
print()
print("Stage 3")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|         O')
print('\t|        \\|')
print('\t|         |')
print('\t|')
print('\t|')
print('\t|')
print('\t-------------')
print()
print("Stage 4")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|         O')
print('\t|        \\|/')
print('\t|         |')
print('\t|')
print('\t|')
print('\t|')
print('\t-------------')
print()
print("Stage 5")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|         O')
print('\t|        \\|/')
print('\t|         |')
print('\t|        /')
print('\t|')
print('\t|')
print('\t-------------')
print()
print("Stage 6")
print()
print('\t|---------|')
print('\t|/        |')
print('\t|         O')
print('\t|        \\|/')
print('\t|         |')
print('\t|        / \\')
print('\t|')
print('\t|')
print('\t-------------')